### PR TITLE
type-fix: Make body optional...

### PR DESCRIPTION
**Pull request by paambaati**
... in the `INetworkRequestResponse` interface. This will help merge cleanly with `LR.IRequest` and fixes https://github.com/LogRocket/logrocket-fuzzy-search-sanitizer/issues/5.

### CODE REVIEW

**Review by pkriete — APPROVED** [review]
Looks good to me! Thank you!

**Comment by gazpachu** [comment]
@pkriete Could you please trigger a release in NPN that includes this fix? 🙏

**Comment by gazpachu** [comment]
Is this repo dead? There hasn't been a new release with the latest changes in a long time

**Comment by gazpachu** [comment]
@pkriete any updates regarding that release?

**Pull request merged**
